---
name: Build
on: workflow_dispatch

env:
  REGISTRY_IMAGE: kirillzak/docker-fedora-ansible

jobs:
  test-build:
    name: Test build of image
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false

      matrix:
        platform:
          - linux/amd64
        version_branch: [35, 36, 37, 38, 39, 40]

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Add Qemu
        uses: docker/setup-qemu-action@v3

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          labels: ${{ steps.meta.outputs.labels }}
          file: ./fedora${{ matrix.version_branch }}/Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},name-canonical=true
          push: false
          tags: |
            kirillzak/docker-fedora-ansible:${{ matrix.version_branch }}
            ghcr.io/${{ github.repository }}:${{ matrix.version_branch }}